### ISSUE TITLE
When I save a dashboard, the result of the put should be used to update the ui

### ISSUE THREAD

**Issue by bettiolo** [dashy-io/dashy-management-console#10]
Right now the object in memory is not updated with the result from the put to ~/dashboards.

To reproduce
- Edit a dashboard
- Set the interval to 1
- Save
- The interval will still be 1
- If you reload the dashboard settings, the interval will be 10

10 is the minimum interval that we allow.

**Comment by bettiolo** [comment]
This is very important, all the calls to the API should return the state of the resource and that state should be used for the UI.

**Comment by mtt87** [comment]
Added client-side validation, I will fetch the new data also after the PUT

**Comment by bettiolo** [comment]
We should do this for every endpoint call

**Comment by bettiolo** [comment]
We should start wrapping this stuff up in an api-client
