### ISSUE TITLE
Add option to hide sticky info header

### ISSUE THREAD

**Issue by mtt87** [dashy-io/dashy-management-console#28]
We should add the option to hide the sticky info header.

For 1.2.0 I'll create a checkbox on the UI and @bettiolo will create the field to track this setting in the dashboard record.

**Comment by bettiolo** [comment]
Ok, but keep in mind that the header is used to let you check that the data on the dashboard is up-to-date. Sometimes raspberry pi crashes and stops refreshing and you notice that if the timer is not counting down. 

Ideas?
